/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calcula.la.distancia.entre.dos.puntos;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Distanciaentre2puntos extends javax.swing.JFrame {

    /**
     * Creates new form Distanciaentre2puntos
     */
    public Distanciaentre2puntos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text_X1 = new javax.swing.JTextField();
        Text_Y1 = new javax.swing.JTextField();
        Button_Calcular = new javax.swing.JButton();
        Button_Limpiar = new javax.swing.JButton();
        Text_X2 = new javax.swing.JTextField();
        Text_Y2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Label_Distancia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distancia entre 2 puntos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/distancia.png"))); // NOI18N

        Text_X1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Text_Y1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Button_Calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Calcular.setText("Calcular");
        Button_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CalcularActionPerformed(evt);
            }
        });

        Button_Limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Text_X2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Text_Y2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("La distancia es :");

        Label_Distancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Distancia.setText("0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/java1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Text_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(Text_X2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Label_Distancia))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Text_Y1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(Text_Y2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(Button_Calcular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Limpiar)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel3))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_X2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_X1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Text_Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Label_Distancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Calcular)
                            .addComponent(Button_Limpiar))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Distancia(){
        //Declaramos 5 variables de tipo double
        double x1, x2, y1, y2, distancia;
        //Condición que evalúa las Text si están vacíos 
        if (Text_Y2.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la distancia de Y2");
            //Colocamos el focus en el Text_Y2
            Text_Y2.requestFocus();
        }else{
          //Condición que evalúa las Text si están vacíos 
        if (Text_Y1.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la distancia de Y1");
            //Colocamos el focus en el Text_Y1
            Text_Y1.requestFocus();
        }else{
           //Condición que evalúa las Text si están vacíos 
            if (Text_X1.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la distancia de X1");
            //Colocamos el focus en el Text_X1
            Text_X1.requestFocus();
        }else{
            //Condición que evalúa las Text si están vacíos 
        if (Text_X2.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese la distancia de X2");
            //Colocamos el focus en el Text_X2
            Text_X2.requestFocus();
        }else{
            /* Funciones que convierte en un tipo double el valor que se ingrese por 
              los Text y lo almacena en las variables x1,x2,y1,y2 */
              x1 = Double.parseDouble(Text_X1.getText());
              x2 = Double.parseDouble(Text_X2.getText());
              y1 = Double.parseDouble(Text_Y1.getText());
              y2 = Double.parseDouble(Text_Y2.getText());
              //Formula para sacar la distancia entre los 2 puntos
              distancia = Math.sqrt(Math.pow(x2-x1,2)+Math.pow(y2- y1,2));
              /* Mostraremos el resultado que este almacenado en la variable 
              distancia en la Label_Distancia */
              Label_Distancia.setText(distancia+"");
        }
      }  
    }  
  }
}     
    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
       Text_X1.setText("");
        Text_X2.setText("");
        Text_Y1.setText("");
        Text_Y2.setText("");
        Label_Distancia.setText("0");
        //Colocamos el focus en el Text_Y2
        Text_Y2.requestFocus();

    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void Button_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CalcularActionPerformed
       Distancia();
    }//GEN-LAST:event_Button_CalcularActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distanciaentre2puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distanciaentre2puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distanciaentre2puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distanciaentre2puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distanciaentre2puntos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Calcular;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JLabel Label_Distancia;
    private javax.swing.JTextField Text_X1;
    private javax.swing.JTextField Text_X2;
    private javax.swing.JTextField Text_Y1;
    private javax.swing.JTextField Text_Y2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
